#!/bin/bash
#
# create_full_emoji-list_to_pipetext.sh
#
# Processes the full emoji list from unicode.org into pipetext.
#
#wget https://unicode.org/emoji/charts/full-emoji-list.html
#
grep name full-emoji-list.html | sed 's/.*td class=>//g' | grep -v '<tr>' | \
    grep -v '<th>' | grep -v 'Unicode emoji' | \
    sed 's/^.................//g' | sed 's/.a href=.*name=[^>]*.//g' | \
    sed 's/<\/a><\/td>//g' | sed 's/<\/td>//g' | \
    sed 's/^colSpan=.*td class=.......//g' | \
    sed 'N;s/\n/ /' | sed 's/U+/|U+/g' | sed 's/ |U/|U/g' > full-emoji-list.ptxt

cat full-emoji-list.ptxt | \
    sed 's/\([^ ]*\) \(.*\)/|\[\2] \1/' | sed 's/⊛ //g' | sed 's/amp;//g' > emoji_name_to_unicode.ptxt

echo "# frozen_string_literal: true" > substitute_emoji_names.rb
echo "# Auto generated by create_full_emoji-list_to_pipetext.sh" >> substitute_emoji_names.rb
echo "\$substitute_emoji_names = {" >> substitute_emoji_names.rb
cat emoji_name_to_unicode.ptxt | \
    sed 's/|\[\(.*\)\] \(.*\)/  \"\1\" \=\> \"\2\"/g' | \
    sed 's/^\(.*\)$/\1,/g' >> substitute_emoji_names.rb
echo "}" >> substitute_emoji_names.rb
cp substitute_emoji_names.rb ruby/lib

cat emoji_name_to_unicode.ptxt | sed 's/|\[\(.*\)\] \(.*\)/|[\1]\t\2\t\1/g' > emoji-test.ptxt

echo "<HTML>" > emoji-test-html.ptxt
echo "<HEAD></HEAD>" >> emoji-test-html.ptxt
echo "<BODY><TABLE>" >> emoji-test-html.ptxt
cat emoji_name_to_unicode.ptxt | \
sed 's/|\[\(.*\)\] \(.*\)/<TR><TD WIDTH=10%>|[\1]<\/TD><TD WIDTH=10%>\2<\/TD><TD>\1<\/TD><\/TR>/g' >> emoji-test-html.ptxt
echo "</TABLE></BODY>" >> emoji-test-html.ptxt
echo "</HTML>" >> emoji-test-html.ptxt
